---
title: A Night In Japan
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: default
- scope:
    path: ''
    type: posts
  values:
    layout: post
email: youjin@hello-earth.org
description: A blog about Japan.
baseurl: 
url: 
twitter_username: itwassme
github_username: itwassme
theme: minima
plugins:
- jekyll-feed
